In [1]:
from datasets import load_dataset

ds = load_dataset("bitext/Bitext-retail-ecommerce-llm-chatbot-training-dataset")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

bitext-retail-ecommerce-llm-chatbot-trai(…):   0%|          | 0.00/42.6M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/44884 [00:00<?, ? examples/s]

In [2]:
ds

DatasetDict({
    train: Dataset({
        features: ['instruction', 'intent', 'category', 'tags', 'response'],
        num_rows: 44884
    })
})

In [3]:
print(ds["train"].column_names)

['instruction', 'intent', 'category', 'tags', 'response']

In [4]:
ds['train']

Dataset({
    features: ['instruction', 'intent', 'category', 'tags', 'response'],
    num_rows: 44884
})

In [5]:
df = ds['train'].to_pandas()
display(df.head())

,instruction,intent,category,tags,response
0,I got to add an item to the cart,add_product,CART,BL,I'll get right on it! I'm here to assist you i...
1,wanna add fucking products to the basket can h...,add_product,CART,BCIMQWZ,I sincerely apologize if you've encountered an...
2,i have to add products to the basket i ned help,add_product,CART,BCMQZ,You bet! I'm here to assist you in adding prod...
3,di like to add products to the cart could i ge...,add_product,CART,BCILMPQZ,Indeed! I'm here to assist you in adding produ...
4,"I need to add an item to the cart , where do I...",add_product,CART,BCILZ,I'll take care of it! I'm here to help you wit...

In [6]:
for col in ['tags','category','intent']:
  print(len(df[col].unique()))

409
13
46

In [7]:
df.drop('tags',axis = 1,inplace = True)

In [8]:
display(df)

,instruction,intent,category,response
0,I got to add an item to the cart,add_product,CART,I'll get right on it! I'm here to assist you i...
1,wanna add fucking products to the basket can h...,add_product,CART,I sincerely apologize if you've encountered an...
2,i have to add products to the basket i ned help,add_product,CART,You bet! I'm here to assist you in adding prod...
3,di like to add products to the cart could i ge...,add_product,CART,Indeed! I'm here to assist you in adding produ...
4,"I need to add an item to the cart , where do I...",add_product,CART,I'll take care of it! I'm here to help you wit...
...,...,...,...,...
44879,I need to report a wrong product,wrong_item,DELIVERY,Our apologies for the inconvenience caused by ...
44880,a fucking prodcut is incorrect can i report it,wrong_item,DELIVERY,I sincerely apologize for the inconvenience ca...
44881,"one of the fucking products I got is wrong, he...",wrong_item,DELIVERY,I'm really sorry to hear that you received the...
44882,"am item is wrong, I need help to report it",wrong_item,DELIVERY,I'm sorry to hear that there was an issue with...
44883,"one of the items I received is incorrect, will...",wrong_item,DELIVERY,We recognize the inconvenience and apologize f...

In [9]:
df

,instruction,intent,category,response
0,I got to add an item to the cart,add_product,CART,I'll get right on it! I'm here to assist you i...
1,wanna add fucking products to the basket can h...,add_product,CART,I sincerely apologize if you've encountered an...
2,i have to add products to the basket i ned help,add_product,CART,You bet! I'm here to assist you in adding prod...
3,di like to add products to the cart could i ge...,add_product,CART,Indeed! I'm here to assist you in adding produ...
4,"I need to add an item to the cart , where do I...",add_product,CART,I'll take care of it! I'm here to help you wit...
...,...,...,...,...
44879,I need to report a wrong product,wrong_item,DELIVERY,Our apologies for the inconvenience caused by ...
44880,a fucking prodcut is incorrect can i report it,wrong_item,DELIVERY,I sincerely apologize for the inconvenience ca...
44881,"one of the fucking products I got is wrong, he...",wrong_item,DELIVERY,I'm really sorry to hear that you received the...
44882,"am item is wrong, I need help to report it",wrong_item,DELIVERY,I'm sorry to hear that there was an issue with...
44883,"one of the items I received is incorrect, will...",wrong_item,DELIVERY,We recognize the inconvenience and apologize f...

In [11]:
import pandas as pd

df = pd.read_csv("hf://datasets/bitext/Bitext-customer-support-llm-chatbot-training-dataset/Bitext_Sample_Customer_Support_Training_Dataset_27K_responses-v11.csv")

In [12]:
df

,flags,instruction,category,intent,response
0,B,question about cancelling order {{Order Number}},ORDER,cancel_order,I've understood you have a question regarding ...
1,BQZ,i have a question about cancelling oorder {{Or...,ORDER,cancel_order,I've been informed that you have a question ab...
2,BLQZ,i need help cancelling puchase {{Order Number}},ORDER,cancel_order,I can sense that you're seeking assistance wit...
3,BL,I need to cancel purchase {{Order Number}},ORDER,cancel_order,I understood that you need assistance with can...
4,BCELN,"I cannot afford this order, cancel purchase {{...",ORDER,cancel_order,I'm sensitive to the fact that you're facing f...
...,...,...,...,...,...
26867,BL,I am waiting for a rebate of {{Refund Amount}}...,REFUND,track_refund,Thank you for sharing your situation regarding...
26868,BIL,how to see if there is anything wrong with my ...,REFUND,track_refund,Ensuring the accuracy of your restitution is o...
26869,BLQZ,I'm waiting for a reimbjrsement of {{Currency ...,REFUND,track_refund,"Firstly, I genuinely understand the importance..."
26870,BL,I don't know what to do to see my reimbursemen...,REFUND,track_refund,I've understood you're unsure about how to che...
26871,BL,I need to know if there is anything new on the...,REFUND,track_refund,It's completely understandable that you want t...

In [14]:
df.drop(['flags','intent','category'],axis = 1,inplace = True)

In [15]:
df

,instruction,response
0,question about cancelling order {{Order Number}},I've understood you have a question regarding ...
1,i have a question about cancelling oorder {{Or...,I've been informed that you have a question ab...
2,i need help cancelling puchase {{Order Number}},I can sense that you're seeking assistance wit...
3,I need to cancel purchase {{Order Number}},I understood that you need assistance with can...
4,"I cannot afford this order, cancel purchase {{...",I'm sensitive to the fact that you're facing f...
...,...,...
26867,I am waiting for a rebate of {{Refund Amount}}...,Thank you for sharing your situation regarding...
26868,how to see if there is anything wrong with my ...,Ensuring the accuracy of your restitution is o...
26869,I'm waiting for a reimbjrsement of {{Currency ...,"Firstly, I genuinely understand the importance..."
26870,I don't know what to do to see my reimbursemen...,I've understood you're unsure about how to che...
26871,I need to know if there is anything new on the...,It's completely understandable that you want t...

In [16]:
df.to_csv('cleaned_data.csv')